package br.com.sgde.estudantes.view;

import br.com.sgde.Exceptions.ExceptionDAO;
import br.com.sgde.dao.CidadeDAO;
import br.com.sgde.dao.EstadoDAO;
import br.com.sgde.dao.PreencheComboBox;
import br.com.sgde.entity.Cidades;
import br.com.sgde.entity.Endereco;
import br.com.sgde.estudantes.controller.StudentController;
import br.com.sgde.estudantes.entity.Student;
import br.com.sgde.estudantes.view.config.StudentCellRenderer;
import br.com.sgde.estudantes.view.config.StudentTableModel;
import br.com.sgde.util.ComboBoxList;
import br.com.sgde.util.LogGenerator;
import br.com.sgde.util.Util;
import br.com.sgde.validation.CPF;
import br.com.sgde.validation.ValidaData;
import br.com.sgde.validation.ValidaNome;
import br.com.sgde.validation.ValidaTelefone;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import java.util.List;
import javax.swing.table.TableRowSorter;
import javax.swing.text.MaskFormatter;
import raven.toast.Notifications;
import java.text.ParseException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author elias
 */
public class EstudantesForm extends javax.swing.JInternalFrame {

    private final PreencheComboBox pcomboBox;
    private final EstadoDAO estadoDAO;
    private final CidadeDAO cidadeDAO;
    private final StudentController studentController;
    private Long idRow;
    private Long idEndereco;

    private MaskFormatter mascaraCpf = null;
    private MaskFormatter mascaraData = null;
    private MaskFormatter mascaraFone = null;
    private MaskFormatter mascaraCep = null;

    public EstudantesForm() throws ExceptionDAO {
        initComponents();

        this.pcomboBox = new PreencheComboBox();
        this.estadoDAO = new EstadoDAO();
        this.cidadeDAO = new CidadeDAO();

        this.studentController = new StudentController();

        preencheComboEstado();
        preencheComboEstadoEnd();
        preencheTabela("");
        tabbedPane.setSelectedIndex(0);
        habilitaBotoes(true);
        habilitaCampos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        tabelaPanel = new javax.swing.JPanel();
        txtPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaStudent = new javax.swing.JTable();
        formularioPanel = new javax.swing.JPanel();
        cbxEstados = new javax.swing.JComboBox<>();
        cbxCidade = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        try {
            mascaraData = new MaskFormatter("##/##/####");
            mascaraData.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            LogGenerator.generateLog(ex.getMessage());
        }
        txtDtaNascimento = new javax.swing.JFormattedTextField(mascaraData);
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNacionalidade = new javax.swing.JTextField();
        cbxUfNascimento = new javax.swing.JComboBox<>();
        cbxCidadeNascimento = new javax.swing.JComboBox<>();
        cbxSexo = new javax.swing.JComboBox<>();
        ckbStatus = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        txtNomeMae = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNomePai = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        try {
            mascaraFone = new MaskFormatter("(##)#####-####");
            mascaraFone.setPlaceholderCharacter('_');
        } catch (ParseException e) {
            LogGenerator.generateLog(e.getMessage());
        }
        txtTelefoneMae = new javax.swing.JFormattedTextField(mascaraFone);
        try {
            mascaraFone = new MaskFormatter("(##)#####-####");
            mascaraFone.setPlaceholderCharacter('_');
        } catch (ParseException e) {
            LogGenerator.generateLog(e.getMessage());
        }
        txtTelefonePai = new javax.swing.JFormattedTextField(mascaraFone);
        jLabel14 = new javax.swing.JLabel();
        txtLogradouro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        try {
            mascaraCep = new MaskFormatter("#####-###");

            mascaraCep.setPlaceholderCharacter('_');
        } catch (ParseException e) {
            LogGenerator.generateLog(e.getMessage());
        }
        txtCep = new javax.swing.JFormattedTextField(mascaraCep);
        try {
            mascaraCpf = new MaskFormatter("###.###.###-##");
            mascaraCpf.setPlaceholderCharacter('_');
        } catch (ParseException e) {
            LogGenerator.generateLog(e.getMessage());
        }
        txtCpf = new javax.swing.JFormattedTextField(mascaraCpf);
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblIncluir = new javax.swing.JLabel();
        lblSalvar = new javax.swing.JLabel();
        lblCancelar = new javax.swing.JLabel();
        lblRemover = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Manutenção de Estudantes");
        setName("estudanteFrame"); // NOI18N
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        txtPesquisa.setHorizontalAlignment(JTextField.LEFT);
        txtPesquisa.putClientProperty("JTextField.leadingIcon", new FlatSVGIcon(getClass().getResource("/images/search_FILL0_wght400_GRAD0_opsz24.svg")));
        txtPesquisa.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Localizar");
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyTyped(evt);
            }
        });

        tabelaStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaStudent);

        javax.swing.GroupLayout tabelaPanelLayout = new javax.swing.GroupLayout(tabelaPanel);
        tabelaPanel.setLayout(tabelaPanelLayout);
        tabelaPanelLayout.setHorizontalGroup(
            tabelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelaPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(tabelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPesquisa)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        tabelaPanelLayout.setVerticalGroup(
            tabelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelaPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Listagem", tabelaPanel);

        cbxEstados.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxEstadosItemStateChanged(evt);
            }
        });

        jLabel2.setText("Nome");

        jLabel3.setText("CPF");

        jLabel4.setText("Data Nascimento");

        jLabel5.setText("Nacionalidade");

        jLabel6.setText("Estado Nascimento");

        jLabel7.setText("Naturalidade");

        jLabel8.setText("Sexo");

        jLabel9.setText("Status");

        cbxUfNascimento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxUfNascimentoItemStateChanged(evt);
            }
        });

        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-Selecione->", "Masculino", "Feminino" }));

        ckbStatus.setText("Ativo");

        jLabel10.setText("Nome da Mãe");

        jLabel11.setText("Nome do Pai");

        jLabel12.setText("Telefone");

        jLabel13.setText("Telefone");

        jLabel14.setText("Logradouro");

        jLabel15.setText("Número");

        jLabel16.setText("Bairro");

        jLabel17.setText("Complemento");

        jLabel18.setText("Estado");

        jLabel19.setText("Cidade");

        jLabel20.setText("CEP");

        javax.swing.GroupLayout formularioPanelLayout = new javax.swing.GroupLayout(formularioPanel);
        formularioPanel.setLayout(formularioPanelLayout);
        formularioPanelLayout.setHorizontalGroup(
            formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17)
                    .addGroup(formularioPanelLayout.createSequentialGroup()
                        .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtDtaNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formularioPanelLayout.createSequentialGroup()
                        .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(formularioPanelLayout.createSequentialGroup()
                                    .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(txtNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                    .addGap(18, 18, 18)
                                    .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbxUfNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbxCidadeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)))
                                .addComponent(txtNomeMae))
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formularioPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9))
                            .addGroup(formularioPanelLayout.createSequentialGroup()
                                .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTelefonePai, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formularioPanelLayout.createSequentialGroup()
                                        .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ckbStatus))
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefoneMae, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(formularioPanelLayout.createSequentialGroup()
                        .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formularioPanelLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(75, 75, 75)
                                .addComponent(jLabel16))
                            .addGroup(formularioPanelLayout.createSequentialGroup()
                                .addComponent(txtNumero)
                                .addGap(18, 18, 18)
                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtComplemento)
                    .addGroup(formularioPanelLayout.createSequentialGroup()
                        .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(cbxEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formularioPanelLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cbxCidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        formularioPanelLayout.setVerticalGroup(
            formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formularioPanelLayout.createSequentialGroup()
                .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formularioPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formularioPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(formularioPanelLayout.createSequentialGroup()
                        .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDtaNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxCidadeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbStatus)))
                    .addComponent(cbxUfNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefoneMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonePai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Formulário", formularioPanel);

        getContentPane().add(tabbedPane);

        jPanel3.setBackground(new java.awt.Color(13, 24, 36));
        jPanel3.setMaximumSize(new java.awt.Dimension(100, 32767));
        jPanel3.setMinimumSize(new java.awt.Dimension(100, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 0));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ESTUDANTES");
        jLabel1.setToolTipText("");

        lblIncluir.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblIncluir.setForeground(new java.awt.Color(255, 255, 255));
        lblIncluir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIncluir.setText("INCLUIR");
        lblIncluir.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Mono", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        lblIncluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIncluirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIncluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIncluirMouseExited(evt);
            }
        });

        lblSalvar.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblSalvar.setForeground(new java.awt.Color(255, 255, 255));
        lblSalvar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalvar.setText("SALVAR");
        lblSalvar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Mono", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        lblSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalvarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalvarMouseExited(evt);
            }
        });

        lblCancelar.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblCancelar.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelar.setText("CANCELAR");
        lblCancelar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Mono", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        lblCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancelarMouseExited(evt);
            }
        });

        lblRemover.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblRemover.setForeground(new java.awt.Color(255, 255, 255));
        lblRemover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRemover.setText("REMOVER");
        lblRemover.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Mono", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        lblRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRemoverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRemoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRemoverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);

        setBounds(0, 0, 1055, 590);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyTyped
        try {
            preencheTabela(txtPesquisa.getText());
        } catch (ExceptionDAO ex) {
            Logger.getLogger(EstudantesForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtPesquisaKeyTyped

    private void tabelaStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaStudentMouseClicked
        this.preencheFormulario();
        this.habilitaCampos(true);
        this.habilitaBotoes(false);
        if (tabbedPane.getSelectedIndex() != 1) {
            tabbedPane.setSelectedIndex(1);
        }
    }//GEN-LAST:event_tabelaStudentMouseClicked

    private void cbxEstadosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxEstadosItemStateChanged
        Integer idUf = this.cbxEstados.getSelectedIndex() + 1;
        List<Cidades> cidades;
        try {
            cidades = this.cidadeDAO.getByCodigoUf(idUf);
            cbxCidade.removeAllItems();
            for (Cidades c : cidades) {
                cbxCidade.addItem(c.getNome());
            }
        } catch (ExceptionDAO ex) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.BOTTOM_LEFT, ex.getMessage());
            LogGenerator.generateLog(ex.getMessage());
        }


    }//GEN-LAST:event_cbxEstadosItemStateChanged

    private void cbxUfNascimentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxUfNascimentoItemStateChanged

        Integer idUf = this.cbxUfNascimento.getSelectedIndex() + 1;
        List<Cidades> cidades;
        try {
            cidades = this.cidadeDAO.getByCodigoUf(idUf);
            cbxCidadeNascimento.removeAllItems();
            for (Cidades c : cidades) {
                cbxCidadeNascimento.addItem(c.getNome());
            }
        } catch (ExceptionDAO ex) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.BOTTOM_LEFT, ex.getMessage());
            LogGenerator.generateLog(ex.getMessage());
        }


    }//GEN-LAST:event_cbxUfNascimentoItemStateChanged

    private void lblIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIncluirMouseClicked
        addAction();
    }//GEN-LAST:event_lblIncluirMouseClicked

    private void lblIncluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIncluirMouseEntered

        lblIncluir.setForeground(Color.YELLOW);
        lblIncluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblIncluirMouseEntered

    private void lblIncluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIncluirMouseExited
        lblIncluir.setForeground(Color.WHITE);
        lblIncluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_lblIncluirMouseExited

    private void lblSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalvarMouseClicked
        Student student;
        Endereco endereco;

        if (!new ValidaNome().valida(this.txtNome.getText().strip())) {
            txtNome.putClientProperty("JComponent.outline", Color.decode("#be2525"));
            txtNome.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);
            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.BOTTOM_LEFT, "Nome é requerido.");
            return;
        } else if (!new CPF(txtCpf.getText().replace(".", "").replace("-", "")).isCPF()) {
            txtCpf.putClientProperty("JComponent.outline", Color.decode("#be2525"));
            txtCpf.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);
            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.BOTTOM_LEFT, "CPF é requerido.");
            return;
        } else if (!new ValidaData("dd/MM/yyyy").valida(txtDtaNascimento.getText().strip())) {
            txtDtaNascimento.putClientProperty("JComponent.outline", Color.decode("#be2525"));
            txtDtaNascimento.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);
            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.BOTTOM_LEFT, "Data é requerida.");
            return;
        } else if (txtNacionalidade.getText().isEmpty()) {
            txtNacionalidade.putClientProperty("JComponent.outline", Color.decode("#be2525"));
            txtNacionalidade.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);
            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.BOTTOM_LEFT, "Nacionalidade é requerida.");
            return;
        } else if (cbxSexo.getSelectedIndex() == 0) {
            cbxSexo.putClientProperty("JComponent.outline", Color.decode("#be2525"));
            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.BOTTOM_LEFT, "Selecione o sexo.");
            return;
        } else if (!new ValidaNome().valida(txtNomeMae.getText().strip())) {
            txtNomeMae.putClientProperty("JComponent.outline", Color.decode("#be2525"));
            txtNomeMae.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);
            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.BOTTOM_LEFT, "Nome da Mãe é requerido.");
            return;
        } else if (!new ValidaTelefone().valida(txtTelefoneMae.getText().strip())) {
            txtTelefoneMae.putClientProperty("JComponent.outline", Color.decode("#be2525"));
            txtTelefoneMae.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);
            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.BOTTOM_LEFT, "Telefone é requerido.");
            return;
        } else if (txtLogradouro.getText().strip().isEmpty()) {
            txtLogradouro.putClientProperty("JComponent.outline", Color.decode("#be2525"));
            txtLogradouro.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);
            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.BOTTOM_LEFT, "Logradouro é requerido.");
            return;
        } else if (txtCep.getText().replace("-", "").strip().isEmpty()) {
            txtCep.putClientProperty("JComponent.outline", Color.decode("#be2525"));
            txtCep.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);
            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.BOTTOM_LEFT, "CEP é requerido.");
            return;
        } else {
            txtNome.putClientProperty("JComponent.outline", null);
            txtCpf.putClientProperty("JComponent.outline", null);
            txtDtaNascimento.putClientProperty("JComponent.outline", null);
            txtNacionalidade.putClientProperty("JComponent.outline", null);
            txtNomeMae.putClientProperty("JComponent.outline", null);
            txtTelefoneMae.putClientProperty("JComponent.outline", null);
            txtLogradouro.putClientProperty("JComponent.outline", null);
            txtCep.putClientProperty("JComponent.outline", null);
            cbxSexo.putClientProperty("JComponent.outline", null);
        }
        
        endereco = new Endereco();

        endereco.setId(this.idEndereco);
        endereco.setLogradouro(txtLogradouro.getText());
        endereco.setNumero(txtNumero.getText());
        endereco.setBairro(txtBairro.getText());
        endereco.setComplemento(txtComplemento.getText());
        endereco.setEstado(cbxEstados.getSelectedItem().toString());
        endereco.setCidade(cbxCidade.getSelectedItem().toString());
        endereco.setCep(new Util().apenasNumero(txtCep.getText()));

        student = new Student(idRow, this.txtNome.getText(), this.txtCpf.getText(),
                new Util().formatDateToUs(this.txtDtaNascimento.getText()), 
                this.cbxSexo.getSelectedItem().toString(), ckbStatus.isSelected(), 
                this.txtNomeMae.getText(), this.txtNomePai.getText(), 
                new Util().apenasNumero(this.txtTelefoneMae.getText()), 
                new Util().apenasNumero(this.txtTelefonePai.getText()), 
                this.txtNacionalidade.getText(), 
                this.cbxUfNascimento.getSelectedItem().toString(), 
                this.cbxCidadeNascimento.getSelectedItem().toString(), endereco);

        try {
            studentController.salvaNoBD(student);
            Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.BOTTOM_LEFT, "Registro salvo  com sucesso.");
            preencheTabela("");
            cancelaAction();
        } catch (ExceptionDAO e) {
            LogGenerator.generateLog(e.getMessage());
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.BOTTOM_LEFT, e.getMessage());
            cancelaAction();
        }
    }//GEN-LAST:event_lblSalvarMouseClicked

    private void lblSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalvarMouseEntered
        lblSalvar.setForeground(Color.YELLOW);
        lblSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblSalvarMouseEntered

    private void lblSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalvarMouseExited
        lblSalvar.setForeground(Color.WHITE);
        lblSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_lblSalvarMouseExited

    private void lblCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseClicked
        try {
            cancelaAction();
        } catch (Exception ex) {
            LogGenerator.generateLog(ex.getMessage());
        }
    }//GEN-LAST:event_lblCancelarMouseClicked

    private void lblCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseEntered
        lblCancelar.setForeground(Color.YELLOW);
        lblCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblCancelarMouseEntered

    private void lblCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseExited
        lblCancelar.setForeground(Color.WHITE);
        lblCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_lblCancelarMouseExited

    private void lblRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoverMouseClicked
        if (this.idRow == null) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um registro na tabela.");
        } else {
            if (JOptionPane.showConfirmDialog(this, "Confirme a exclusão do item.", "Confirmação",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                try {
                    Student student = new Student();
                    student.setId(idRow);
                    studentController.removeItem(student);
                    Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.BOTTOM_LEFT, "Registro removido com sucesso.");
                    preencheTabela("");
                    cancelaAction();
                } catch (ExceptionDAO ex) {
                    LogGenerator.generateLog(ex.getMessage());
                    Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.BOTTOM_LEFT, "Ocorreu um erro durante a exclusão.");
                    cancelaAction();
                }
            } else {
                cancelaAction();
            }
        }
    }//GEN-LAST:event_lblRemoverMouseClicked

    private void lblRemoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoverMouseEntered
        lblRemover.setForeground(Color.YELLOW);
        lblRemover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblRemoverMouseEntered

    private void lblRemoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoverMouseExited
        lblRemover.setForeground(Color.WHITE);
        lblRemover.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_lblRemoverMouseExited

    private void cancelaAction() {
        limpaCampos();
        habilitaBotoes(true);
        habilitaCampos(false);
        preencheComboEstado();
        preencheComboEstadoEnd();
        if (this.idRow != null) {
            this.idRow = null;
        }
        if (this.idEndereco != null) {
            this.idEndereco = null;
        }
        tabelaStudent.clearSelection();
        if (tabbedPane.getSelectedIndex() != 0) {
            tabbedPane.setSelectedIndex(0);
        }
    }

    private void addAction() {
        limpaCampos();
        habilitaBotoes(false);
        habilitaCampos(true);
        preencheComboEstado();
        preencheComboEstadoEnd();
        if (this.idRow != null) {
            this.idRow = null;
        }
        if (this.idEndereco != null) {
            this.idEndereco = null;
        }
        tabelaStudent.clearSelection();
        if (tabbedPane.getSelectedIndex() != 1) {
            tabbedPane.setSelectedIndex(1);
        }
        Notifications.getInstance().show(Notifications.Type.INFO, Notifications.Location.BOTTOM_LEFT, "Em modo de edição.");
    }

    private void limpaCampos() {
        this.txtNome.setText(null);
        this.txtCpf.setText(null);
        this.txtDtaNascimento.setText(null);
        this.txtNacionalidade.setText(null);
        this.cbxUfNascimento.getModel().setSelectedItem("Tocantins");
        this.cbxSexo.setSelectedIndex(0);
        this.ckbStatus.setSelected(false);
        this.txtNomeMae.setText(null);
        this.txtTelefoneMae.setText(null);
        this.txtNomePai.setText(null);
        this.txtTelefonePai.setText(null);

        txtLogradouro.setText(null);
        txtNumero.setText(null);
        txtBairro.setText(null);
        txtComplemento.setText(null);
        cbxEstados.getModel().setSelectedItem("Tocantins");
        txtCep.setText(null);
    }

    private void habilitaCampos(boolean valor) {
        this.txtNome.setEnabled(valor);
        this.txtCpf.setEnabled(valor);
        this.txtDtaNascimento.setEnabled(valor);
        this.txtNacionalidade.setEnabled(valor);
        this.cbxUfNascimento.setEnabled(valor);
        this.cbxCidadeNascimento.setEnabled(valor);
        this.cbxSexo.setEnabled(valor);
        this.ckbStatus.setEnabled(valor);
        this.txtNomeMae.setEnabled(valor);
        this.txtTelefoneMae.setEnabled(valor);
        this.txtNomePai.setEnabled(valor);
        this.txtTelefonePai.setEnabled(valor);

        txtLogradouro.setEnabled(valor);
        txtNumero.setEnabled(valor);
        txtBairro.setEnabled(valor);
        txtComplemento.setEnabled(valor);
        cbxEstados.setEnabled(valor);
        cbxCidade.setEnabled(valor);
        txtCep.setEnabled(valor);
    }

    private void habilitaBotoes(boolean valor) {
        lblIncluir.setEnabled(valor);
        lblSalvar.setEnabled(!valor);
        lblCancelar.setEnabled(!valor);
    }

    private void preencheComboEstado() {
        this.pcomboBox.comboBoxEstado();
        cbxEstados.removeAllItems();
        for (ComboBoxList c : this.pcomboBox.getList()) {
            cbxEstados.addItem(c.toString());
        }

    }

    private void preencheComboEstadoEnd() {
        this.pcomboBox.comboBoxEstado();
        cbxUfNascimento.removeAllItems();
        for (ComboBoxList c : this.pcomboBox.getList()) {
            cbxUfNascimento.addItem(c.toString());
        }
    }

    private void preencheTabela(String valor) throws ExceptionDAO {
        List<Student> studentList = this.studentController.buscaPeloValor(valor);
        StudentTableModel modelo = new StudentTableModel(studentList);
        tabelaStudent.setModel(modelo);
        tabelaStudent.setDefaultRenderer(Object.class, new StudentCellRenderer());
        tabelaStudent.setRowSorter(new TableRowSorter<>(tabelaStudent.getModel()));
    }

    private void preencheFormulario() {
        int row = this.tabelaStudent.getSelectedRow();
        if (row != -1) {
            Long id = Long.valueOf(this.tabelaStudent.getValueAt(row, 0).toString());
            var estudante = new Student();

            try {
                estudante = this.studentController.getPeloID(id);
                this.idRow = estudante.getId();

                this.txtNome.setText(estudante.getNome());
                this.txtCpf.setText(estudante.getCpf());
                this.txtDtaNascimento.setText(new Util().formatDate(estudante.getDta_nasc()));
                this.txtNacionalidade.setText(estudante.getNacionalidade());
                this.cbxUfNascimento.getModel().setSelectedItem(estudante.getUfNascimento());
                this.cbxCidadeNascimento.getModel().setSelectedItem(estudante.getCidadeNascimento());
                this.cbxSexo.getModel().setSelectedItem(estudante.getSexo());
                this.ckbStatus.setSelected(estudante.isStatus());
                this.txtNomeMae.setText(estudante.getNomeMae());
                this.txtTelefoneMae.setText(estudante.getTelefoneMae());
                this.txtNomePai.setText(estudante.getNomePai());
                this.txtTelefonePai.setText(estudante.getTelefonePai());

                Endereco e = estudante.getEndereco();
                this.idEndereco = e.getId();
                txtLogradouro.setText(e.getLogradouro());
                txtNumero.setText(e.getNumero());
                txtBairro.setText(e.getBairro());
                txtComplemento.setText(e.getComplemento());
                cbxEstados.getModel().setSelectedItem(e.getEstado());
                cbxCidade.getModel().setSelectedItem(e.getCidade());
                txtCep.setText(e.getCep());

            } catch (Exception e) {
                LogGenerator.generateLog(e.getMessage());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxCidade;
    private javax.swing.JComboBox<String> cbxCidadeNascimento;
    private javax.swing.JComboBox<Object> cbxEstados;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JComboBox<String> cbxUfNascimento;
    private javax.swing.JCheckBox ckbStatus;
    private javax.swing.JPanel formularioPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblIncluir;
    private javax.swing.JLabel lblRemover;
    private javax.swing.JLabel lblSalvar;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JPanel tabelaPanel;
    private javax.swing.JTable tabelaStudent;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDtaNascimento;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtNacionalidade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeMae;
    private javax.swing.JTextField txtNomePai;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JFormattedTextField txtTelefoneMae;
    private javax.swing.JFormattedTextField txtTelefonePai;
    // End of variables declaration//GEN-END:variables

}
